name: GrowStick
main: io.github.rypofalem.growstick.GrowStickPlugin
version: 4
api-version: 1.13
website: rypofalem.github.io
author: RypoFalem
description: Use an item to make plants grow faster.
commands:
permissions:
  growstick.use:
    description: Use the growstick.
    default: true