name: GrowStick
main: io.github.rypofalem.growstick.GrowStickPlugin
version: 1.9.4-1.1
website: rypofalem.github.io
author: RypoFalem
description: Use an item to make plants grow faster.
softdepend: [Skills]
commands:
permissions:
  growstick.use:
    escription: Use the growstick.
    default: true
  